"""add complete user location

Revision ID: 8e5d8de0fea3
Revises: 6895a31a4d2d
Create Date: 2026-09-30 08:59:37.553991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5d8de0fea3'
down_revision = '6895a31a4d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
